src/Countrynside/SiteBundle/Entity/Util.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Region
 *
 * @author G3_Julien
 */

namespace Countrynside\SiteBundle\Entity;

class Util {

    public static function getRegion() {
        $region = array(
            "Alsace" => "Alsace",
            "Aquitaine" => "Aquitaine",
            "Auvergne" => "Auvergne",
            "Basse-Normandie" => "Basse-Normandie",
            "Bourgogne" => "Bourgogne",
            "Bretagne" => "Bretagne",
            "Centre" => "Centre",
            "Champagne-Ardenne" => "Champagne-Ardenne",
            "Corse" => "Corse",
            "Franche-Comté" => "Franche-Comté",
            "Haute-Normandie" => "Haute-Normandie",
            "Île-de-France" => "Île-de-France",
            "Languedoc-Roussillon" => "Languedoc-Roussillon",
            "Limousin" => "Limousin",
            "Lorraine" => "Lorraine",
            "Midi-Pyrénées" => "Midi-Pyrénées",
            "Nord-Pas-de-Calais" => "Nord-Pas-de-Calais",
            "Pays de la Loire" => "Pays de la Loire",
            "Picardie" => "Picardie",
            "Poitou-Charentes" => "Poitou-Charentes",
            "Provence-Alpes-Côte d'Azur" => "Provence-Alpes-Côte d'Azur",
            "Rhône-Alpes" => "Rhône-Alpes"
        );
        return $region;
    }

    public static function getCapacite() {
        $cap = array(
            1 => "1 personne",
            2 => "2 personnes",
            3 => "3 personnes",
            4 => "4 personnes",
            5 => "5 personnes",
            10 => "+10 personnes",
            50 => "+50 personnes",
            100 => "+100 personnes",
        );
        return $cap;
    }

    public static function getType() {
        $type = array(
            "Randonnée",
            "Festival",
            "Visite culturelle",
            "Spectacle",
            "Autre",
        );
        return $type;
    }

}

src/Countrynside/SiteBundle/Controller/DefaultController.php
<?php

namespace Countrynside\SiteBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Countrynside\SiteBundle\Entity\Event;
use Countrynside\CalendarBundle\Entity\Item;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class DefaultController extends Controller {

    public function indexAction() {
        return $this->render('CountrynsideSiteBundle:Default:index.html.twig');
    }
    
    public function connexionAction() {
        return $this->render('CountrynsideSiteBundle:Default:connexion.html.twig');
    }

    public function annonceAction(Request $request) {

        $user = $this->getUser();
        $event = new Event();
        $item = new Item();
        $event->setDatePub(new \DateTime());
        $event->setUser($user);

        $form = $this->createForm('event', $event);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $this->get('session')->getFlashBag()->add(
                    'valid', 'Votre annonce a bien été sauvegardée'
            );
            $em = $this->getDoctrine()->getManager();
            $event->upload($user->getId());
            $em->persist($event);
            $item->setIdEvent($event);
            $item->setName($event->getTitre());
            $item->setPosition(0);
            $em->persist($item);
            $em->flush();
            return $this->redirect($this->generateUrl('countrynside_site_mes_annonces'));
        }
        return $this->render('CountrynsideSiteBundle:Default:annonce.html.twig', array(
                    'form' => $form->createView(),
        ));
    }

    public function mesAnnoncesAction() {
        $id = $this->getUser()->getId();
        $user = $this->getDoctrine()
                ->getRepository('CountrynsideUserBundle:User')
                ->find($id);

        $events = $user->getEvents();
        // var_dump($events);
        return $this->render('CountrynsideSiteBundle:Default:voir.html.twig', array('events' => $events, 'id' => $id));
    }

    public function chercherEventAction(Request $request) {
        if ($request->getMethod() == "GET") {
            $user = $this->getUser();
            $this->testPremium($user);
            $recherche = $request->get("infos_recherche");
            $dateD = $request->get("dateD");
            $dateF = $request->get("dateF");
            $mots = explode(" ", $recherche);
            $events = $this->getDoctrine()
                    ->getManager()
                    ->getRepository('CountrynsideSiteBundle:Event')
                    ->findByMots($mots);
        }
        $eventsList = $this->get('knp_paginator')->paginate($events, $this->get('request')->query->get('page', 1), 6);
        return $this->render('CountrynsideSiteBundle:Default:rechercherEvennement.html.twig', array('user' => $user, 'events' => $eventsList));
    }

   /* public function infosEventCompletAction(Request $request) {
        $user = $this->getUser();
        $event = null;
        if ($this->testPremium($user)) {
            $id_event = $request->get('event');
            $event = $this->getDoctrine()
                    ->getRepository('CountrynsideSiteBundle:Event')
                    ->find($id_event);
            return $this->render('CountrynsideSiteBundle:Default:infosEvennementComplet.html.twig', array('event' => $event, 'user' => $user));
        }
        return $this->redirect($this->generateUrl('countrynside_site_abonnement'));
    }*/

    public function testPremium(&$user){
        $test = false;
        if ($user->isPremium()){
            $time = new \DateTime("now");
            if($time > $user->getDateExpiration()){
                $user->setPremium(false);
                $user->setDateExpiration(null);
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();
            } 
            else{
                $test = true;
            }
        }
        return $test;
    }
    public function abonnementAction(Request $request) {
        $user = $this->getUser();
        $offres = $this->getDoctrine()
                ->getRepository('CountrynsidePaymentBundle:Offre')
                ->findAll();
        return $this->render('CountrynsidePaymentBundle:Default:abonnement.html.twig', array('offres' => $offres, 'user' => $user));
    }

}

src/Countrynside/SiteBundle/Resources/views/Default/annonce.html.twig
{% extends '::base.html.twig'%}
{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" href="{{ asset('css/sitebundle/css/eventform.css') }}" type="text/css" />
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
    <script type="text/javascript" src="{{ asset('css/sitebundle/js/eventform.js') }}"></script>
{% endblock %}

{%block body%}
    {{parent()}}
    <body onload="initialize()">
        <div class="container">
            <div class="text-center">
                <div class="col-md-12">
                    <fieldset class>
                        <h3 class="headtitle">Publiez votre évènement</h3>
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="form-group col-md-12">
                                {{ form_row(form.titre,{'attr' : {'class':'form-control', 'placeholder' : 'Entrez le titre de votre annonce'}}) }}
                            </div>    
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                {{ form_row(form.type,{'attr' : {'class':'form-control'}}) }}
                            </div>    
                        </div>
                        <div class="row">

                        </div>
                        <div class="row">
                            <div id="locationField" class="form-group col-md-12">
                                {{ form_row(form.adresse,{'attr' : {'id' : 'autocomplete','class':'form-control', 'placeholder' : 'Entrez votre addresse',
             'onFocus' : 'geolocate()'}}) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                {{ form_row(form.region,{'attr' : {'class':'form-control', 'placeholder' : 'Veuillez saisir votre addresse',}}) }}
                            </div>

                            <div class="form-group col-md-6">
                                {{ form_row(form.telephone,{'attr' : {'class':'form-control', 'placeholder' : 'Entrez votre numéro de téléphone'}}) }}
                            </div>        
                        </div>
                        <div class="row">
                            <div class="form-group col-md-9">
                                {{ form_row(form.file,{'attr' : {'class':'form-control'}}) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                {{ form_row(form.capacite,{'attr' : {'class':'form-control'}}) }}
                            </div>    
                            <div class="form-group col-md-6">
                                {{ form_row(form.tarif,{'attr' : {'class':'form-control'}}) }}
                            </div>    
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                {{ form_row(form.descriptif,{'attr' : {'class':'form-control'}}) }}
                            </div>    
                        </div>
                        <input type="submit" class="btn btn-success"/>
                        {{ form_errors(form) }}
                        {{ form_end(form) }}
                    </fieldset>
                </div>    
            </div>
        </div>
    </div>
</body>
{%endblock%}    

src/Countrynside/SiteBundle/Resources/views/Default/connexion.html.twig
{% extends '::base.html.twig'%}
{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" href="{{ asset('css/connexion.css') }}" type="text/css" />
{% endblock %}
{%block body%}
    {{parent()}}
    <div class="container">
        <div class="text-center">
            <h3>Connexion</h3>
        </div>
</div>
{%endblock%}    

src/Countrynside/SiteBundle/Resources/views/Default/devenirPremium.html.twig
{% extends '::base.html.twig'%}
{% block body %}
{{ parent()}}
<div class="container main">
    <h3> Devenir Premium </h3>
</div>

{% endblock body %}

src/Countrynside/SiteBundle/Resources/views/Default/infosEvennementComplet.html.twig
{% extends '::base.html.twig'%}
{% block body %}
{{ parent()}}
<div class="container">
    {% if user.premium %}
        {{event.descriptif}}
    {% else %}
    <p> L'accès à ces informations est restreint, vous devez vous procurer un compte premium <p>
    <p> <a href="{{path("blog_home")}}"> </a> Devenir premium </p>
    {% endif %}
</div>
{% endblock body %}

src/Countrynside/SiteBundle/Resources/views/Default/rechercherEvennement.html.twig
{% extends '::base.html.twig'%}
{% block stylesheets %}
    {{parent()}}
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="{{ asset('css/sitebundle/css/eventform.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/sitebundle/css/font-awesome-4.1.0/css/font-awesome.min.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/datepicker/css/datepicker.css') }}" type="text/css" />
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="http://maps.google.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{{ asset('css/sitebundle/js/eventmap.js') }}"></script>
    <script src="{{ asset('css/datepicker/js/bootstrap-datepicker.js') }}"></script>
     <script>
        $(function(){
            $('.datepicker').datepicker();
        })
    </script>
{% endblock %}
{% block body %}
    {{parent()}}
    {% set directory= "users/documents/" %}
    <div class="row text-center" style="margin-bottom: 50px;">
        <div class="search-pannel">
            <div class="row col-xs-12">
                <form class="form-inline col-xs-12" role="form" method="GET" action="{{path("countrynside_site_chercherEvent")}}">
                    <div class="form-group">
                        <input type="text" class="form-control input-search col-xs-3" name="infos_recherche" placeholder="Que cherchez vous ?">
                    </div>
                    <div class="form-group">
                        <input class="form-control input-search col-xs-3 datepicker" type="text" name="dateD" placeholder="Quand... ?">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control input-search col-xs-3 datepicker" name="dateF" placeholder="Jusqu'à... ?">
                    </div>
                    <button type="submit" class="btn btn-default">Chercher</button>
                </form>
            </div>
        </div>
    </div>
        {% if events is empty %}
            <p style="margin-top: 75px"> Aucun évennement trouvé </p>
        {% else %}
                <div class="container main">
                    {% for event in events %}
                        <div id="card">
                            <div class="col-md-4 col-sm-6 card-item" >
                                {% if not user.isPremium %}
                                <a href="{{path('countrynside_site_abonnement', {'event' : event.id} )}} " class="card-link" >
                                {% else %}
                                <a href="#cardModal{{ event.id }}" class="card-link" data-toggle="modal">
                                {%endif%}
                                    <div class="card-hover">
                                        <div class="card-hover-content">
                                            <i class="fa fa-plus fa-3x"></i>
                                        </div>
                                    </div>
                                    {% if event.path %}
                                        <img src="{{asset(directory~event.user.id~"/photos/"~event.path)}}" alt="{{event.titre}}"  class="image-card img-responsive"/>
                                    {% else %}
                                        <img src="{{asset('bundles/countrynside/images/photo_default.png')}}" class="image-card img-responsive"/>
                                    {% endif %}
                                   </a>
                                <div class="card-caption">
                                    <h4 class="card-title">{{event.titre}}</h4><br/>
                                    <p class="text-muted">{{event.descriptif}}</p>
                                </div>
                            </div>
                        </div>

                        <!-- card Modal -->
                        <div class="card-modal modal fade" id="cardModal{{ event.id }}" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-content">
                                <div class="close-modal" data-dismiss="modal">
                                    <div class="lr">
                                        <div class="rl">
                                        </div>
                                    </div>
                                </div>
                                <div class="container">
                                    <div class="row">
                                        <div class="container">
                                            <div class="modal-body">
                                                <h4 class="card-title">{{event.titre}}</h4>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        {% if event.path %}
                                                            <img src="{{asset(directory~event.user.id~"/photos/"~event.path)}}" alt="{{event.titre}}"  class="img-responsive element-center"/>
                                                        {% else %}
                                                            <img src="{{asset('bundles/countrynside/images/photo_default.png')}}" class="img-responsive element-center"/>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <p style="text-align: justify">
                                                        {{ event.descriptif }}
                                                    </p>
                                                </div>

                                                <div class="text-left">
                                                    <i class="glyphicon glyphicon-calendar"></i><span class="modal-label"> Date de publication :</span>
                                                    <time>{{event.datepub|date('d M Y')}}</time>
                                                </div>
                                                <div class="text-left">
                                                    <i class="glyphicon glyphicon-globe"></i><span class="modal-label"> Région :</span>
                                                    {{event.region}}
                                                </div>
                                                <div class="text-left">
                                                    <i class="glyphicon glyphicon-map-marker"></i><span class="modal-label"> Adresse :</span>
                                                    {{event.adresse}}
                                                </div>
                                                <div class="text-left">
                                                    <i class="glyphicon glyphicon-phone"></i><span class="modal-label"> Téléphone :</span>
                                                    {{event.telephone}}
                                                </div>
                                                <div class="text-left">
                                                    <i class="glyphicon glyphicon-inbox"></i><span class="modal-label"> Capacité :</span>
                                                    {% if event.capacite == 1 %}
                                                        {{event.capacite}} personne
                                                    {% elseif event.capacite > 1 and event.capacite < 10 %}
                                                        {{event.capacite}} personnes
                                                    {% else %}
                                                        + {{event.capacite}} personnes
                                                    {% endif %}
                                                </div>
                                                <div class="text-left">
                                                    <i class="glyphicon glyphicon-euro"></i><span class="modal-label"> Tarif :</span>
                                                    {{event.tarif}}
                                                </div>
                                                {#<div class="text-left">#}
                                                    {#<i class="glyphicon glyphicon-edit"></i><span class="modal-label"> <a href="{{ path('countrynside_calendar_admin', { 'event': event.id })}}">Gérer les disponibilités</a></span>#}
                                                {#</div>#}
                                                <div class="text-left">
                                                    <i class="glyphicon glyphicon-info-sign"></i> <span class="modal-label"> <a href="{{ path('countrynside_calendar_homepage', { 'event': event.id })}}" target="_blank">Voir les disponibilités</a></span>
                                                </div>
                                                <a href="#mapModal" data-toggle="modal"><input type="button" class="btn btn-primary"  value="Voir l'emplacement sur la carte"></a>
                                                <div class="col-xs-12" style="margin-top: 50px">
                                                    <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>

                <div class="card-modal modal fade" id="mapModal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-content">
                        <div class="close-modal" data-dismiss="modal">
                            <div class="lr">
                                <div class="rl">
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="container">
                                    <div class="modal-body">
                                        <div id="map-canvas" style="width: 100%; height: 500px; padding: 0; margin: 0" >
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        {% endif %}
        {# display navigation #}
        <div class="row navigation text-center">
            {{ knp_pagination_render(events) }}
        </div>
    <script type="text/javascript">
        var map;
        var myCenter=new google.maps.LatLng(46.6302142, 2.5680160);
        var marker=new google.maps.Marker({
            position:myCenter
        });

        function initialize() {
            var mapProp = {
                center:myCenter,
                draggable: false,
                scrollwheel: true,
                mapTypeId:google.maps.MapTypeId.ROADMAP,
                zoom: 6,
                disableDefaultUI: true
            };

            map=new google.maps.Map(document.getElementById("map-canvas"),mapProp);
            marker.setMap(map);

            google.maps.event.addListener(marker, 'click', function() {

                infowindow.setContent(contentString);
                infowindow.open(map, marker);

            });
        };
        google.maps.event.addDomListener(window, 'load', initialize);

        google.maps.event.addDomListener(window, "resize", resizingMap());

        $('#mapModal').on('show.bs.modal', function() {
            //Must wait until the render of the modal appear, thats why we use the resizeMap and NOT resizingMap!! ;-)
            resizeMap();
        })

        function resizeMap() {
            if(typeof map =="undefined") return;
            setTimeout( function(){resizingMap();} , 400);
        }

        function resizingMap() {
            if(typeof map =="undefined") return;
            var center = map.getCenter();
            google.maps.event.trigger(map, "resize");
            map.setCenter(center);
        }
    </script>
{% endblock body %}